name: 'Create Vercel deployment'
description: 'Create a new production or preview Vercel deployment'

inputs:
  vercel-team-id:
    description: 'Vercel team id'
    required: true
  vercel-project-id:
    description: 'Vercel project id'
    required: true
  vercel-token:
    description: 'Vercel token to authenticate'
    required: true
  vercel-cli-version:
    description: Vercel CLI version to use
    required: false
    default: 'latest'
  vercel-is-production:
    description: Wheter or not use --prod and --environment=production for commands
    required: false
    default: 'false'
  local-build:
    description: Wheter or not to build the project locally or in vercel
    required: false
    default: 'false'
  github-comment:
    description: 'Create comment on the pull request or commit with the deployment information'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token used to create the pull request comment'
    required: false

outputs:
  deployment-url:
    description: 'URL of the created deployment'
  preview-alias-url:
    description: 'Branch alias URL for the deployment'

runs:
  using: 'node20'
  main: 'dist/index.js'
