name: Deploy to vercel

on:
  workflow_call:
    secrets:
      vercel-team-id:
        description: 'Vercel team id'
        required: true
      vercel-project-id:
        description: 'Vercel project id'
        required: true
      vercel-token:
        description: 'Vercel token to authenticate'
        required: true
      github-token:
        description: 'GitHub token used to create the pull request comment'
        required: false
    inputs:
      environment:
        description: 'The deploy environment'
        required: true
        type: string
      github-comment:
        description: 'Create comment on the pull request or commit with the deployment information'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Setup Nextjs cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/app/.next/cache
          key: nextjs-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Deploy to Vercel
        id: deploy
        uses: ./
        with:
          vercel-team-id: ${{ secrets.vercel-team-id }}
          vercel-project-id: ${{ secrets.vercel-project-id }}
          vercel-token: ${{ secrets.vercel-token }}
          vercel-is-production: ${{ inputs.environment == 'Production' }}
          github-comment: ${{ inputs.github-comment }}
          github-token: ${{ secrets.github-token }}
      - name: Print deployment URL
        run: |
          echo "Deployment URL: ${{ steps.deploy.outputs.deployment-url }}"
          echo "Alias URL: ${{ steps.deploy.outputs.preview-alias-url }}"
