name: Release main

on:
  push:
    branches:
      - main

jobs:
  code-checks:
    name: Run code checks and quality tools
    uses: ./.github/workflows/_code_checks.yaml

  release:
    name: Create a new production release
    needs: [code-checks]
    uses: ./.github/workflows/_sem_release.yaml

  deploy:
    name: Deploy to vercel
    needs: [release]
    if: needs.release.outputs.new-release-published == 'true'
    uses: ./.github/workflows/_deploy_vercel.yaml
    with:
      environment: Production
    secrets:
      vercel-team-id: ${{ secrets.VERCEL_ORG_ID }}
      vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
