name: Check PR

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-commits:
    name: Lint commits
    uses: ./.github/workflows/_lint_commits.yaml

  code-checks:
    name: Run code checks and quality tools
    uses: ./.github/workflows/_code_checks.yaml

  deploy-web:
    name: Deploy to vercel
    needs: [code-checks]
    uses: ./.github/workflows/_deploy_vercel.yaml
    with:
      environment: Preview
      github-comment: true
    secrets:
      vercel-team-id: ${{ secrets.VERCEL_ORG_ID }}
      vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
